{
  "language": "python",
  "python": "2.7",
  "install": [
    "pip install -r requirements.txt",
    "pip install codecov",
    "pip install pytest-cov"
  ],
  "addons": [
    "apt": [
      "packages": [
        "python-requests",
        "python-coverage",
        "python-mock",
        "python-dev",
        "libmysqlclient-dev"
      ]
    ]
  ],
  "services": [
    "mysql"
  ],
  "before_install": [
    "mysql -uroot -e \"grant all on fisrt_test.* to user_ci@localhost identified by '1234'\"",
    "mysql -uroot -e \"drop database if exists fisrt_test\"",
    "mysql -uroot -e \"create database fisrt_test\""
  ],
  "script": [
    "coverage run manage.py create:module -n users",
    "coverage run manage.py init_db"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux",
  "after_success": [
    "codecov"
  ]
}

